# Generated by Django 5.1.7 on 2025-03-16 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_modeluser_subscriber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeluser",
            name="subscriber",
        ),
        migrations.AddField(
            model_name="modeluser",
            name="subscriber",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="blog_subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
    ]
