# Generated by Django 5.1.7 on 2025-03-08 13:07

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Краткое название тематики")),
                ("description", models.CharField(max_length=50, verbose_name="Небольшое описание тематики")),
            ],
            options={
                "verbose_name": "тематику",
                "verbose_name_plural": "Тематика",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("blog_text", ckeditor.fields.RichTextField(verbose_name="Содержимое статьи")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/%Y/%m/%d/", verbose_name="Превью (изображение)"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовать")),
                ("view_count", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
                ("like", models.PositiveIntegerField(default=0, verbose_name="Количество лайков")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "subscriber",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blog_subscriber",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Подписчик",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topic",
                        to="blog.topic",
                        verbose_name="Тематика блога",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статью",
                "verbose_name_plural": "Статьи",
                "ordering": ["created_at"],
            },
        ),
    ]
