# Generated by Django 5.1.7 on 2025-03-23 13:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("blog_text", ckeditor.fields.RichTextField(verbose_name="Содержимое статьи")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/%Y/%m/%d/", verbose_name="Превью (изображение)"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Поставте галочку, что-бы запись видели все",
                        verbose_name="Опубликовать",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False,
                        help_text="Поставте галочку, что-бы добавить оплату",
                        verbose_name="Платный контент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статью",
                "verbose_name_plural": "Статьи",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaidBlog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "цена",
                "verbose_name_plural": "Цена",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateField(blank=True, null=True, verbose_name="Дата оплаты")),
                ("link", models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату")),
                ("session_id", models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии")),
                (
                    "status",
                    models.CharField(
                        choices=[("create", "Создан"), ("paid", "Оплачен")],
                        default="create",
                        max_length=10,
                        verbose_name="Статус оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Краткое название тематики")),
                ("description", models.CharField(max_length=50, verbose_name="Небольшое описание тематики")),
            ],
            options={
                "verbose_name": "тематику",
                "verbose_name_plural": "Тематика",
                "ordering": ["title"],
            },
        ),
    ]
