# Generated by Django 5.1.7 on 2025-03-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("blog_text", models.TextField(verbose_name="Содержимое статьи")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/%Y/%m/%d/", verbose_name="Превью (изображение)"
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовать")),
                ("view_count", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
                ("like", models.PositiveIntegerField(default=0, verbose_name="Количество лайков")),
            ],
            options={
                "verbose_name": "Статью",
                "verbose_name_plural": "Статьи",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=50, verbose_name="Краткое название тематики")),
                ("description", models.CharField(max_length=50, verbose_name="Небольшое описание тематики")),
            ],
            options={
                "verbose_name": "Тематика",
                "verbose_name_plural": "Тематика",
                "ordering": ["title"],
            },
        ),
    ]
