# Generated by Django 5.1.7 on 2025-03-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="blog_subscriber", to=settings.AUTH_USER_MODEL, verbose_name="Лайкнули"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="paidblog",
            name="paid_blog",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="blog.blog",
                verbose_name="Блог",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="buyers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.AddField(
            model_name="paidblog",
            name="payments",
            field=models.ManyToManyField(
                blank=True, related_name="paid", to="blog.payment", verbose_name="Покупатель"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="topic",
                to="blog.topic",
                verbose_name="Тематика блога",
            ),
        ),
    ]
