# Generated by Django 5.1.7 on 2025-03-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="subscriber",
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(
                default=True, help_text="Поставте галочку, что-бы запись видели все", verbose_name="Опубликовать"
            ),
        ),
    ]
